### ISSUE TITLE
When yml_path.is_file(), yml_file variable is undefined

### ISSUE THREAD

**Issue by nadiucc-profesia** [lmc-eu/luft#2]
When I try to execute jdbc load task for a specific single yaml file (instead of folder with yaml files), I get this error:

_UnboundLocalError: local variable 'yml_file' referenced before assignment_

It can be found in this part of the code: 

**/work/luft/common/task_list.py**

https://github.com/lmc-eu/luft/blob/master/luft/common/task_list.py#L105

**Comment by tomsej** [comment]
@nadiucc-profesia can you look at it. It should be fixed now.
